# Generated by Django 3.0.5 on 2020-04-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=60)),
                ('is_corrupt', models.BooleanField()),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_card_type', to='presidente.CardType', verbose_name='Card Type')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_card_type', to='presidente.CardType', verbose_name='Requirements')),
            ],
        ),
    ]
