# Generated by Django 3.0.5 on 2020-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidente', '0002_auto_20200413_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='only_attacks_corrupt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_corrupt',
            field=models.BooleanField(default=False),
        ),
    ]
