# Generated by Django 3.0.5 on 2020-04-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presidente', '0005_auto_20200413_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackcard',
            name='attack_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_card_attack_type', to='presidente.CardType', verbose_name='Card Attack Type'),
        ),
    ]
