# Generated by Django 3.0.5 on 2020-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidente', '0006_attackcard_attack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='emoji',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
