# Generated by Django 3.0.5 on 2020-04-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidente', '0007_cardtype_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='emoji',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
